---
  - hosts: all
    vars:
      mongodb_password: "changeme"
    tasks:
      - name: Install git && easy_install
        apt:
          name: "{{ item }}"
          state: present
        with_items:
          - git
          - python-setuptools
          - curl
        register: task
        sudo: yes

      - name: Install pip
        easy_install: name=pip
        sudo: yes

      - name: Install Docker
        shell: curl -sSL https://get.docker.com/ | sh
        args:
          creates: /usr/bin/docker
        sudo: yes

      - name: Install docker-py
        pip:
          name: "{{item}}"
        with_items:
          - httplib2
          - docker-py
        sudo: yes

      - name: Upload node-docker dev image
        synchronize: src=node-docker dest=/home/vagrant

      - name: Create directory to store code
        file:
      	  path: /home/code/theoreticalcoding/branches/dev
      	  state: directory
      	  mode: 0755

      - name: Upload theoreticalcoding code files
        synchronize: src=blog dest=/home/code/theoreticalcoding/branches/dev

      - name: Build Docker image for Theoretical Coding site
        docker_image:
          path: /home/vagrant/node-docker
          name: theoreticalcoding/node-docker
          state: present

      - name: Start MongoDB Container
        docker:
          name: MongoDB
          image: tutum/mongodb
          ports:
            - 27017
          env:
            MONGODB_PASS:{{ mongodb_password }}
          state: started

      - name: Start Site container
        docker:
          name: theoreticalcoding-node
          image: theoreticalcoding/node-docker
          link:
            - "MongoDB"
          state: started
